# Generated by Django 4.2.4 on 2023-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("image_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=15, unique=True)),
                ("title", models.CharField(max_length=50)),
                (
                    "author",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("categories", models.ManyToManyField(to="content.category")),
            ],
        ),
    ]
